language: r
dist: trusty
sudo: false
cache: packages

os:
  - linux

r:
 - 3.2
 - 3.3
 - 3.4
 - release
 - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
